# Generated by Django 4.1.2 on 2022-10-20 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pictures", "0001_initial"),
        ("answers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="pod",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="pictures.pod",
            ),
            preserve_default=False,
        ),
    ]
